version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
     TZ: Europe/Paris
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
            TZ: Europe/Paris
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
   grafana-storage: {}
   prometheus-data: {}
