version: '3'

services:
  mysql:
    image: mariadb:10.1.23
    container_name: mysql
    env_file: docker-compose.env
    restart: always
    ports:
      - "3306:3306"
    volumes:
        - ./docker/mysql/:/var/lib/mysql/
    logging:
      driver: json-file
      options:
        max-size: "100m"
  myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST= mysql
        restart: always
