version: '3'
services:
   mongodb:
                  hostname: mongodb
                  image: mongo:latest
                  ports:
                    - "27017:27017"
                  volumes:
                    - ./data:/data/db:rw
                    - ./001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
                    - ./mongodb_config:/data/configdb
                      #command: mongod --auth --smallfiles --logpath=/dev/null # --quiet
                  environment:
                    - MONGO_DATA_DIR=/data/db
                    - MONGO_LOG_DIR=/dev/null
                    - MONGO_INITDB_DATABASE=devops
                    - MONGO_INITDB_ROOT_USERNAME=admin
                    - MONGO_INITDB_ROOT_PASSWORD=devops
